# This file should contain all the record creation needed to seed the database with its default values.
# The data can then be loaded with the rake db:seed (or created alongside the db with db:setup).
#
# Examples:
#
#   cities = City.create([{ name: 'Chicago' }, { name: 'Copenhagen' }])
#   Mayor.create(name: 'Emanuel', city: cities.first)

Sex.create(name:"Masculino")
Sex.create(name:"Femenino")

Size.create(name:"S (hasta 45 x 45 cm)")
Size.create(name:"M (hasta 65 x 65 cm)")
Size.create(name:"L (hasta 95 x 95 cm)")
Size.create(name:"XL (hasta 150 x 150 cm)")
Size.create(name:"XL (mayor de 150 x 150 cm)")

Orientation.create(name:"Square")
Orientation.create(name:"Portrait")
Orientation.create(name:"Landscape")

Technique.create(name:"Acrílico")
Technique.create(name:"Acuarela")
Technique.create(name:"Assemblage")
Technique.create(name:"Cera")
Technique.create(name:"Gouache")
Technique.create(name:"Industrial")
Technique.create(name:"Lápiz")
Technique.create(name:"Lápiz")
Technique.create(name:"Media Mixta")
Technique.create(name:"Óleo")
Technique.create(name:"Otros")
Technique.create(name:"Pastel")
Technique.create(name:"Rotulador")
Technique.create(name:"Tinta")
Technique.create(name:"Vidrio")

Style.create(name:"Art Deco")
Style.create(name:"Art Nouveau y modernismo")
Style.create(name:"Arte abstracto")
Style.create(name:"Arte Conceptual")
Style.create(name:"Arte écológico")
Style.create(name:"Arte Urbano")
Style.create(name:"Arte figurativo")
Style.create(name:"Arte naíf")
Style.create(name:"Arte Pop")
Style.create(name:"Clasicismo")
Style.create(name:"Contemporáneo")
Style.create(name:"Cubismo")
Style.create(name:"Dadaísmo")
Style.create(name:"Documental")
Style.create(name:"Expresionismo")
Style.create(name:"Expresionismo abstracto")
Style.create(name:"Fauvismo")
Style.create(name:"Fotorrealismo")
Style.create(name:"Ilustración")
Style.create(name:"Impresionismo")
Style.create(name:"Land Art")
Style.create(name:"Minimalismo")
Style.create(name:"Modernismo")
Style.create(name:"Paper arts")
Style.create(name:"Popular")
Style.create(name:"Realismo")
Style.create(name:"Retrato")
Style.create(name:"Simbolismo")
Style.create(name:"Surrealismo")
Style.create(name:"Trampantojo")


Subject.create(name:" Animales")
Subject.create(name:" Arquitectura")
Subject.create(name:" Artes Escénicas")
Subject.create(name:" Blanco y Negro")
Subject.create(name:" Bodegones")
Subject.create(name:" Botánica")
Subject.create(name:" Caligrafía")
Subject.create(name:" Ciencias y Tecnologías")
Subject.create(name:" Cine y Celebridades")
Subject.create(name:" Ciudades")
Subject.create(name:" Comida y bebida")
Subject.create(name:" Cultura")
Subject.create(name:" Deportes")
Subject.create(name:" Desnudos")
Subject.create(name:" Educación")
Subject.create(name:" Espacios exteriores")
Subject.create(name:" Espiritualidad")
Subject.create(name:" Estaciones del año")
Subject.create(name:" Familia")
Subject.create(name:" Fantasía")
Subject.create(name:" Figuras")
Subject.create(name:" Flores")
Subject.create(name:" Geométrico")
Subject.create(name:" Grafiti")
Subject.create(name:" Humor")
Subject.create(name:" Interiores")
Subject.create(name:" Mitología clásica")
Subject.create(name:" Moda")
Subject.create(name:" Mortalidad")
Subject.create(name:" Música y baile")
Subject.create(name:" Niños")
Subject.create(name:" Otros")
Subject.create(name:" Paisajes")
Subject.create(name:" Pared")
Subject.create(name:" Religión")
Subject.create(name:" Retratos")
Subject.create(name:" Salud y Belleza")
Subject.create(name:" Surrealismo")
Subject.create(name:" Tebeos, cómics, dibujos animados")
Subject.create(name:" Transportes")
Subject.create(name:" Viajes")